plugins {
    id 'java'
    id 'application'
    id 'groovy'
}

group = 'org.alan'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = 'org.alan.todolist.TodoList'
}

dependencies {
    testImplementation 'org.codehaus.groovy:groovy:3.0.19'
    testImplementation 'org.spockframework:spock-core:2.3-groovy-3.0'
}

test {
    useJUnitPlatform()
}

run {
    standardInput = System.in
}